version: "3"
services:
  client:
    image: nkp217/client:latest
    expose:
      - "3000"

  server:
    image: nkp217/server:latest
    expose:
      - "8000"

  nginx:
    restart: always
    image: nkp217/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - client
      - server
