version: "3"
services:
  client:
    build: nkp217/client:latest
    expose:
      - "3000"

  server:
    build: nkp217/server:latest
    expose:
      - "8000"

  nginx:
    restart: always
    image: nginx:1.19-alpine
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - server
